language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

jdk: oraclejdk8

 env:
   matrix:
     - ANDROID_TARGET=android-26  ANDROID_ABI=armeabi-v7a

 before_install:
  - chmod +x gradlew

 script:
   - ./gradlew build check