language: android

jdk: oraclejdk8

 env:
   matrix:
     - ANDROID_TARGET=android-26  ANDROID_ABI=armeabi-v7a

 android:
   components:
     - tools
     - platform-tools

     # The BuildTools version used by your project
     - build-tools-26.0.2

     # The SDK version used to compile your project
     - $ANDROID_TARGET

 before_install:
  - chmod +x gradlew

 script:
   - ./gradlew build check