  on_success: never
  on_failure: always

before_install:
  - yes | sdkmanager "platforms;android-28"

language: android

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.2


    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google-apis-google-26

    #Specify
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-17

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-2742d1c5'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

